### PR TITLE
enable build machinery

### PR DESCRIPTION
**Pull request by sanchezl**
Prepared repo for integration into openshift CI.
- pull in build-machinery and provided new Makefile
- Added `Dockerfile`s for CI and releases images
- ensured `make build`, `make test-unit`, `make verify` and `make images` work.
- moved to `go.mod` 
Once merged, https://github.com/openshift/release/pull/5286 will enable CI test jobs.

### CODE REVIEW

**Comment by deads2k** [comment]
Can you open this against a branch instead of master or is this a CI restriction thing?

**Comment by sanchezl** [comment]
> Can you open this against a branch instead of master or is this a CI restriction thing?

CI restriction. CI will also auto-create and manage the release-x.y branches.

**Comment by stlaz** [comment]
@sanchezl shouldn't we get a CI on this repo first so that we know nothing breaks with this patch or is this more like chicken egg where we can't create the config in `openshift/release` because it wouldn't know how to build our containers here and so the CI there would fail?

**Comment by sanchezl** [comment]
> @sanchezl shouldn't we get a CI on this repo first so that we know nothing breaks with this patch or is this more like chicken egg where we can't create the config in `openshift/release` because it wouldn't know how to build our containers here and so the CI there would fail?

https://github.com/openshift/release/pull/5286, which enables CI, wont merge until its `pj-rehearse` jobs are green, and that wont happen until this PR is merged.

**Comment by deads2k** [comment]
gotta start somewhere.

**Pull request merged**
