### PR TITLE
OCPBUGS-6231: Update golang version and ART images

### PR DESCRIPTION
**Pull request by dinhxuanvu**
Signed-off-by: Vu Dinh <vudinh@outlook.com>

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Since this is the upstream fork you'll need to do the update in `UPSTREAM: <carry>` commits similar to what @sanchezl did in https://github.com/openshift/kubernetes-kube-storage-version-migrator/pull/185 to make it easier to rebase.

**Comment by dinhxuanvu** [comment]
@dgrisonnet Does this look better?

**Comment by dgrisonnet** [comment]
Perfect :+1: 

/lgtm

/assign @sanchezl

**Pull request merged**
